export const dataSpec = () => {
    return {
        "store": {
            "id": 0,
            "number": 0,
            "name": "",
            "countryCode": "UK"
        },
        "register": {
            "id": 0,
            "storeId": 0,
            "number": 0,
            "status": "",
            "lastTxnNumber": -1
        },
        "view": {
            "name": "",
            "title": "",
            "message": "",
            "form": {
                "targetView": "HOME",
                "serverProcess": null,
                "elements": null,
            },
            "functionButtons": [],
        },
        "uiTranslations": {
            "administrator": "",
            "associate": "",
            "check": "",
            "currencySymbol": "",
            "date": "",
            "devmessage1": "",
            "devmessage2": "",
            "devmessage3": "",
            "devmessage4": "",
            "difference": "",
            "edit": "",
            "header": "",
            "items": "",
            "keyboard": "",
            "lineTotal": "",
            "lineValue": "",
            "logo": "",
            "manager": "",
            "number": "",
            "password": "",
            "product": "",
            "quantity": "",
            "reference": "",
            "register": "",
            "returnedQuantity": "",
            "role": "",
            "status": "",
            "store": "",
            "storeName": "",
            "subtotal": "",
            "tenderTotal": "",
            "time": "",
            "total": "",
            "transaction": "",
            "transactionLines": "",
            "transactionTotal": "",
            "type": "",
            "user": "",
            "value": ""
        },
        "basket": [],
        "tender": [],
        "user": {
            "id": 0,
            "code": "",
            "email": "",
            "name": ""
        },
        "error": "",
        "report": null,
    }
}

